routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('receita', 'ReceitasController');
Route::resource('despesa', 'DespesasController');

app/Banco.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banco extends Model
{
    //
}

app/Contato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    //
}

app/ControleCaixa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ControleCaixa extends Model
{
    //
}

app/Despesa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Despesa extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $table = 'despesas';
    protected $fillable = [
        'data',
        'descricao'
    ];
}

app/Endereco.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Endereco extends Model
{
    //
}

app/MercadoriaEntrada.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MercadoriaEntrada extends Model
{
    //
}

app/MercadoriaSaida.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MercadoriaSaida extends Model
{
    //
}

app/Pessoa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pessoa extends Model
{
    //
}

app/Produto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    //
}

app/Promissoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Promissoria extends Model
{
    //
}

app/Receita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Receita extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $table = 'receitas';
    protected $fillable = [
        'data',
        'descricao'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DespesasController.php
<?php

namespace App\Http\Controllers;

use App\Despesa;
use Illuminate\Http\Request;

class DespesasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Despesa $despesas)
    {
        return view('despesa.index', ['despesas' => $despesas->paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('despesa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $despesa = new Despesa();
        $despesa->data = $request->input('data');
        $despesa->descricao = $request->input('descricao');
        $despesa->valor = $request->input('valor');
        $despesa->save();

        return redirect()->route('despesa.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ReceitasController.php
<?php

namespace App\Http\Controllers;

use App\Receita;
use Illuminate\Http\Request;

class ReceitasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Receita $receitas)
    {
        return view('receita.index', ['receitas' => $receitas->paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('receita.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $receita = new Receita();
        $receita->data = $request->input('data');
        $receita->descricao = $request->input('descricao');
        $receita->valor = $request->input('valor');
        $receita->save();

        return redirect()->route('receita.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/despesa/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card col-lg-6">
        <div class="card-body">
            <form method="post" action="{{ route('despesa.store') }}">
                @csrf
                <label>Data</label>
                <input class="form-control" type="date" name="data">

                <label>Descrição</label>
                <input class="form-control" type="text" name="descricao">

                <label>Valor</label>
                <input class="form-control" type="text" name="valor">

                <button class="btn btn-success" type="submit">Salvar</button>
            </form>
        </div>
    </div>
@endsection

resources/views/despesa/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card col-lg-6">
        <div class="card-header">
            <a class="btn btn-sm btn-primary" type="button" href="{{ route('home') }}">
                Home
            </a>
            <a class="btn btn-sm btn-info" type="button" href="{{ route('despesa.create') }}">
                Lançar
            </a>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Data</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Valor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach( $despesas as $despesa)
                        <tr>
                            <td>{{ date( 'd/m/Y', strtotime($despesa->data)) }}</td>
                            <td>{{ $despesa->descricao }}</td>
                            <td>{{ $despesa->valor }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{ $despesas->links() }}
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <a class="btn btn-success" type="button" href="{{ route('receita.index') }}">Receita</a>
                    <a class="btn btn-danger" type="button" href="{{ route('despesa.index') }}">Despesa</a>
                </div>
            </div>
        </div>
        <table-component></table-component>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>LS Creativy</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    LS Creativy
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/receita/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card col-lg-6">
        <div class="card-body">
            <form method="post" action="{{ route('receita.store') }}">
                @csrf
                <label>Data da Receita</label>
                <input class="form-control" type="date" name="data">
                <label>Descrição da Receita</label>
                <input class="form-control" type="text" name="descricao">
                <label>Valor</label>
                <input class="form-control" type="text" name="valor">
                <button class="btn btn-success" type="submit">Salvar</button>
            </form>
        </div>
    </div>
@endsection

resources/views/receita/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card col-lg-6">
        <div class="card-header">
            <a class="btn btn-sm btn-primary" type="button" href="{{ route('home') }}">
                Home
            </a>
            <a class="btn btn-sm btn-info" type="button" href="{{ route('receita.create') }}">
                Lançar
            </a>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Data</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Valor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach( $receitas as $receita )
                    <tr>
                        <td>{{ date( 'd/m/Y', strtotime($receita->data)) }}</td>
                        <td>{{ $receita->descricao }}</td>
                        <td>{{ $receita->valor }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{ $receitas->links() }}
        </div>
    </div>
@endsection